### ISSUE TITLE
Unable to install WikiExtractor v3.0.4

### ISSUE THREAD

**Issue by CharZae** [akb89/witokit#14]
Hi,

Thanks for this awesome tool. However, I can't find a way to install it. 

Here is my config:

- Python 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0] on linux
- Pip v20.0.2

Here is the error message:

```bash
ERROR: Could not find a version that satisfies the requirement wikiextractor==3.0.4 (from witokit) (from versions: 0.1)
ERROR: No matching distribution found for wikiextractor==3.0.4 (from witokit)
```

Apparently, only the v0.1 exists on PyPi.

Thanks for your help,

Best,

Charlotte.

**Comment by akb89** [comment]
Ok I found the origin of the bug: pip removed support for dependency_links in version 19.0 (see https://stackoverflow.com/questions/26061610/pip-install-dependency-links) so pip install no longer works. Doing a python3 setup.py install after a git clone should thought. You can try that and let me know if it works while I work on a more robust fix.

**Comment by ghost** [comment]
Thank you for the alternative solution, I managed to install Witokit and its dependencies. However, I am not sure I did it successfully as these commands below failed. Would you have any tips on what I did wrong? 
```
(venv-dev) charly@Archy:~/Documents/work/modules/WITOKIT$ witokit download ⁠--lang fr --date latest --output /home/charly/Documents/work/ --num-threads 3
usage: witokit [-h] {download,extract,process,sample} ...
witokit: error: unrecognized arguments: ⁠--lang fr
(venv-dev) charly@Archy:~/Documents/work/modules/WITOKIT$ witokit download ⁠--lang en --date latest --output /home/charly/Documents/work/ --num-threads 3
usage: witokit [-h] {download,extract,process,sample} ...
witokit: error: unrecognized arguments: ⁠--lang en
```
Thank you so much for your help !

**Comment by akb89** [comment]
Weird, I cannot replicate the error. Could should show me the output of `witokit download --help` please?

**Comment by ghost** [comment]
```
(venv-dev) charly@Archy:~/Documents/work/modules/WITOKIT$ witokit download --help
usage: witokit download [-h] [-l LANG] [-d DATE] -o OUTPUT_DIRPATH
                        [-n NUM_THREADS]

optional arguments:
  -h, --help            show this help message and exit
  -l LANG, --lang LANG  the language ISO code of the Wikipedia dump to
                        download (default: en)
  -d DATE, --date DATE  the date of the Wikipedia dump to download (default:
                        latest)
  -o OUTPUT_DIRPATH, --output OUTPUT_DIRPATH
                        absolute path to output directory where to save
                        downloaded files (default: None)
  -n NUM_THREADS, --num-threads NUM_THREADS
                        number of CPU threads to use (default: 1)
```

**Comment by akb89** [comment]
What happens if you run `witokit download ⁠--date latest --output /home/charly/Documents/work/ --num-threads 3` without specifying the `--lang en` parameter?

**Comment by ghost** [comment]
```
(venv-dev) charly@Archy:~/Documents/work/modules/WITOKIT$ witokit download ⁠--date latest --output /home/charly/Documents/work/ --num-threads 3
usage: witokit [-h] {download,extract,process,sample} ...
witokit: error: unrecognized arguments: ⁠--date latest
```

I fear I did something wrong during the installation... I will try to reinstall it from scratch one more time and keep you posted. Thank you so much for your help!

**Comment by akb89** [comment]
Ok, let me know if you manage to make it work

**Comment by ghost** [comment]
So, the mistake was indeed on my side. Witokit works perfectly!
I inadvertently put some non-breaking spaces before arguments (either from typing too fast or pasting it from SublimeText), which triggered the error. 
Once again, thank you both for your efficient tool and your time !
